### ISSUE TITLE
Nginx and letsencrypt failed

### ISSUE THREAD

**Issue by Linuxman827** [stickz/rtinst#1]
Installing nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.

Same error on both Debian 10 and Ubuntu 20.04 on a dedicated OVH server.

Had to force it with sudo systemctl restart nginx 
I can then connect to unsecure selfsigned ip/rutorrent but does not work with domain/rutorrent

**Comment by Hobostar** [comment]
Same here, it seems that there is something wrong with the flow of the script. 
In my record, letsencrypt fails for the first time and then goes to the self-signed certificate. In the installation's final stage, the script will claim that letsencrypt is executed and modify the nginx setting. In fact, no certificate is issued, failing nginx.

Manually run `rtletsencrypt` once, and restart the system after the `nginx -t` check is passed, and it should be worked.

You may also need to delete the `/var/www/rutorrent/plugins/autodl-irssi` directory, the maintainer canceled the installation of irssi in the main script, but forgot to delete it in rutorrent

**Comment by Linuxman827** [comment]
Same as above. 
Letsencrypt certificate is installed with success message but i can only connect to ip/rutorrent, not the domain/rutorrent info from rtinst.info.

**Comment by Hobostar** [comment]
> Same as above.
> Letsencrypt certificate is installed with success message but i can only connect to ip/rutorrent, not the domain/rutorrent info from rtinst.info.

Editing the nginx site configuration file should solve your problem, but this fork seems to have customized too many settings, I decided to switch back to the original version (using the rtletsencrypt script in this fork)

**Comment by stickz** [comment]
hi @Linuxman827 thanks for this issue report. I was able to reproduce this problem with nginx and letsencrypt. The nginx service does not restart properly after the configuration files are edited with the successfully generated ssl certificate. I'm adding `fuser -k 80/tcp` and `fuser -k 443/tcp` to the script shortly to resolve this problem.

hi @Hobostar this fork is customized to run on a dedicated server. If this is not your intention, then I would definitely recommend using the original version instead. I made this for my dedicated servers and wanted to share it for other people.

**Comment by Linuxman827** [comment]
Updated script and did rtinst without rtorrent compiling, and the same error is occurring with the same nginx error code during install.
Have to do sudo rtletsencrypt and force restart nginx to be able to connect to selfsigned cert.

**Comment by stickz** [comment]
Could you run `journalctl -xe` and post your nginx errors here? The problem I was able to reproduce and fix was binding errors.
`nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)`

I added the following commands to fix this issue and restart nginx. It could be that a sleep is required, if you have these errors. 
```
sudo fuser -k 80/tcp
sudo fuser -k 443/tcp
sudo service nginx restart
```

Also, try running these commands and posting the output. It could be that your domain is not configured properly.
```
export serverip=$(ip route get 8.8.8.8 | awk 'NR==1 {print $7}')
export serverdn=$(perl -MSocket -le "print((gethostbyaddr(inet_aton('$serverip'), AF_INET))[0])")
export
```

After exporting variables run this command to generate the ssl certificate, to see if there's any errors with that process.
`sudo certbot -q --nginx --register-unsafely-without-email --agree-tos certonly -d $serverdn`

**Comment by Linuxman827** [comment]
Cant really find anything in journal because its over 3400 lines with same stuff repeated. The only error i could find is sudo[1030]: pam_unix(sudo:auth): Couldn't open /etc/securetty: No such file or directory

The 2 export commands gives blank result, nothing happens.

But sudo certbot command gives me: Challenge failed for domain xxx.dedi.leaseweb.net
Some challenges have failed.

Thanks btw for your help and maintaining the rtinst script !

**Comment by stickz** [comment]
I modified the rtletsencrypt script to exit gracefully if "Challenge failed for domain" appears again. https://github.com/stickz/rtinst/commit/276bc12eb49450650d3279717dab1a52f0f7682c My guess is that it was updating the nginx configuration file with an invalid certificate, which was causing the process to fail to start. Go ahead and give these new changes a test run and see what happens. I can't test this properly for a week because I hit the ratelimit of 50 requests per week.

You will need to address the issue with the domain you're trying to register a certificate for, if you want to use a certificate for it. I know that Hetzner works with xxx.xxx.xxx.xxx.clients.your-server.de because I've tested this. You can try editing your hosts file in `/etc/hosts` with using a free service like xxx.xxx.xxx.xxx.nip.io by replacing the x's with your ip address.
```
127.0.0.1 localhost.localdomain localhost
xxx.xxx.xxx.xxx  xxx.xxx.xxx.xxx.nip.io
```

**Comment by Linuxman827** [comment]
Did reinstall the server and updated script and ran rtinst.
cat /opt/rtinst/rtletsencrypt gives error:

nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/xxx.nip.io/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/xxx.nip.io/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] cannot load certificate "/etc/letsencrypt/live/xxx.nip.io/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen(\'/etc/letsencrypt/live/xxx.nip.io/fullchain.pem\',\'r\') error:2006D080:BIO routines:BIO_new_file:no such file)\nnginx: configuration file /etc/nginx/nginx.conf test failed\n')

Perhaps try to rollback todays changes and i will try again with the nip.io domain

**Comment by stickz** [comment]
Sorry about that. I just launched a cloud server and tested the nip.io domain. I fixed a bunch of problems with the script and got it working. Go ahead and give it anther try. `/opt/rtinst/rtletsencrypt` is gone now because it's not compatible with the script. 

I had to restore the nginx configuration file and successfully launch the nginx service before the cerbot command could be run. This is what those errors were about. This problem is resolved now.

It should work from both the `sudo rtinst` and `sudo rtletsencrypt ` standpoints now. The script aims to be fully portable, so there's no need to reinstall your operating system. If it fails, it will try everything over again, similar to how a fresh reinstall works.

**Comment by Linuxman827** [comment]
Thank you for updates.
On my already installed server the update worked with both letsencrypt cert and nginx. 

But on my other identical server, i get the same error during both rtinst, rtletsencrypt and restart nginx.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
unable to generate certificates

This is with both the original leaseweb and nip.io domain.

**Comment by Linuxman827** [comment]
> 
> 
> Thank you for updates.
> On my already installed server the update worked with both letsencrypt cert and nginx.
> 
> But on my other identical and freshly installed Ubuntu 20.04 server, i get the same error during both rtinst, rtletsencrypt and restart nginx.
> 
> > Job for nginx.service failed because the control process exited with error code.
> > See "systemctl status nginx.service" and "journalctl -xe" for details.
> > Certificates Generated
> > Lets Encrypt Certificates installed
> > Installing nginx
> > Job for nginx.service failed because the control process exited with error code.
> > See "systemctl status nginx.service" and "journalctl -xe" for details.
> 
> This is with both the original leaseweb and nip.io domain.

I solved the problem by generating a selfsigned cert first, then do rtletsencrypt and then restart nginx.
Perhaps add it to the main script so installs wont fail on new installs. 

Thanks again for maintaining the rtinst script, much appreciated!

**Comment by ahmed2m** [comment]
Me too, with rtinst from the latest changes I still get:
```
...
No snaps are installed yet. Try 'snap install hello-world'.
Installing certbot
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Certificates Generated
Lets Encrypt Certificates installed
Installing nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Installing c-ares
Installing curl
...
```
With `nginx -c /etc/nginx/nginx.conf -t` the error is:
```
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/domainname.xyz/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/domainname.xyz/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed
```
But then this is solved as @Linuxman827 said with just `sudo certbot certonly -d domainname.xyz` then starting nginx

**Comment by stickz** [comment]
hi, would anyone like to confirm this issue has been resolved with fresh installs? 

I updated the script to generate the self-signed certificates first. Then attempt to install the letsencrypt certificate afterwards. If letsencrypt fails for whatever reason, nginx will launch with the self-signed certificates.

**Comment by ahmed2m** [comment]
Seems it does work but the certificate for some reason is generated for the ip **only** not the domain name

and this is what I got in the logs:
```
...
No snaps are installed yet. Try 'snap install hello-world'.
Installing certbot
unable to install certificates
Self signed certificats installed
Installing nginx
Installing c-ares
...

```

**Comment by Linuxman827** [comment]
Tried latest build on freshly installed Ubuntu 20.04 and does not work with nip.io domain out of box.
After install it was only a ip selfsigned cert generated.
Still have to do the manuel workaround to get it working.

What i had to do on fresh Ubuntu was:
- change domain in /etc/hosts
- run rtinst
- reboot
- run sudo rtadmin option 9
- run sudo rtletsencrypt
- run sudo systemctl restart nginx

**Comment by stickz** [comment]
Thanks for testing this, I see what is happening. We're very close to a working build. The package manager is replacing the nginx configuration file. And cerbot requires a working https configuration on nginx to generate the letsencrypt certificate, without any user intervention. This is why it works properly on the second attempt at running the script and not the first attempt.

I'm firing up a cloud server right now and resolving this problem. I'm also going to resolve the problem where if the user disables IPV6 support on their operating system, it will require two attempts to pass the install script instead of one attempt.

**Comment by Linuxman827** [comment]
Latest build does not work for me. 
I cant even do the manual workaround for installing the letsencrypt cert.

How can i install 83cb846 instead of latest one?

**Comment by Linuxman827** [comment]
I cant get the latest build working with lets encrypt even with the manual workaround.
Tried deleting rtinst and downloading a earlier build and  do sudo ./rtsetup inside folder but does not work.
What is the correct way of downgrading?

**Comment by stickz** [comment]
Yes, there is a weekly rate limit of 50 letsencrypt certificates per domain. nip.io was probably used up for this week because I've been testing it as well. There was no changes made to the letsencrypt script that would cause it to otherwise fail. "Unable to install certificates" prevents an attempt to install a certificate that is not there and causing nginx to fail to start.

I am still in the process of testing and making further changes to the script. I will switch to anther domain on the weekend and resume testing. There is a couple more things I need to iron out, that is preventing letsencrypt from working on the first attempt.

Also, Debian 10 compiles the binaries with GCC 8 which is why I recommend using Ubuntu 20.04 LTS. This is currently running on GCC 9. The script will bump Ubuntu 20.04 LTS to GCC 10 in the not too distant future through configuration changes. There is no easy way to accomplish this on Debian 10, without making the script take 45m to complete on most systems. The latest version of this compiler is crucial, if you want rutorrent, rtorrent and the full software stack to run with the best possible performance.

Debian 10 is however stable with this script (but not the arakasi72 script) because it manually updates the curl version. The package curl version on Debian 10 will cause rtorrent to crash in some cases. This a version specific issue with a critical software component.

**Comment by Linuxman827** [comment]
Alright thank you, i will try next week then.
The reason i wanted Debain10 is that i wanted Deluge 1.3.15 installed from source.
Cant do this on Ubuntu 20 due to lack of python2, so it was either Debian 10 or Ubuntu 18.04

I would like to add i have been adding some sysctl.conf tweaks for additional boost to performance. Also enabling the TCP BBR.
As seen here: [https://www.techrepublic.com/article/how-to-enable-tcp-bbr-to-improve-network-speed-on-linux/](url)
rclone speed went from 80mb/s to maxing out gbit pipe 112mb/s
rtorrent is also maxing out gbit.

> vm.swappiness = 1
fs.file-max = 1000000
kernel.pid_max = 4194303
kernel.sched_migration_cost_ns = 5000000
kernel.sched_autogroup_enabled = 0
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_no_metrics_save = 0
net.ipv4.tcp_abort_on_overflow = 0
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_tw_reuse = 1
vm.dirty_background_ratio = 10
vm.dirty_ratio = 30
net.ipv4.tcp_rfc1337 = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_fack = 1
net.ipv4.tcp_workaround_signed_windows = 1
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_orphan_retries = 2
net.ipv4.tcp_retries2 = 8
net.ipv4.ip_local_port_range = 1024 65535
net.core.netdev_max_backlog = 3240000
net.core.somaxconn = 50000
net.ipv4.tcp_max_tw_buckets = 262144
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_fin_timeout = 60
net.ipv4.tcp_keepalive_time = 7200
net.ipv4.tcp_keepalive_intvl = 75
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.ip_no_pmtu_disc = 0
net.core.rmem_default = 16777216
net.core.wmem_default = 16777216
net.core.optmem_max = 16777216
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.netdev_budget = 200000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_rmem = 4096 524000 67110000
net.ipv4.tcp_wmem = 4096 524000 67110000
net.ipv4.tcp_adv_win_scale = 2
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control = bbr

**Comment by stickz** [comment]
If you have ruTorrent working properly, there shouldn't be any need for deluge. You can create multiple users if required.

It's my intention to update this script in the future with some sysctl tweaks for increased throughput. I went through your list and added a few of them to my master list. Currently, I have the following settings:

```
fs.file-max = 65535

# Some network settings
net.ipv4.tcp_fin_timeout = 20
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_congestion_control=bbr

# Maximum Socket Receive Buffer. 16MB per socket - which sounds like a lot, but will virtually never consume that much. Default: 212992
net.core.rmem_max = 16777216
# Maximum Socket Send Buffer. 16MB per socket - which sounds like a lot, but will virtually never consume that much. Default: 212992
net.core.wmem_max = 16777216
# Increase the write-buffer-space allocatable: min 4KB, def 12MB, max 16MB. Default: 4096 16384 4194304
net.ipv4.tcp_wmem = 4096 12582912 16777216
# Increase the read-buffer-space allocatable: min 4KB, def 12MB, max 16MB. Default: 4096 16384 4194304
net.ipv4.tcp_rmem = 4096 12582912 16777216

# Disable the TCP timestamps option for better CPU utilization
net.ipv4.tcp_timestamps=0
# Enable the TCP selective acks option for better throughput
net.ipv4.tcp_sack=1
# Increase the maximum length of processor input queues
net.core.netdev_max_backlog=250000
# Enable low latency mode for TCP
net.ipv4.tcp_low_latency=1
```

**Comment by Linuxman827** [comment]
Im trying Deluge2 headless from repo atm. Looks like it performs well.

This issue could be closed now i think since both nginx and letsencrypt works on new installs.
Thank you very much for all support and your work on rtinst :)

Just remember to also add `net.core.default_qdisc=fq` to sysctl.conf to enable TCP BBR.

**Comment by stickz** [comment]
> Just remember to also add `net.core.default_qdisc=fq` to sysctl.conf to enable TCP BBR.
The default on Ubuntu 20.04 LTS is fq_codel and the linux kernel version is 5.4. Any Linux kernel after 4.13 will work with fq_codel.
